services:
  db:
    image: mariadb:10
    container_name: techpass_db
    environment:
      - MARIADB_DATABASE=techpassdb
      - MARIADB_USER=userTech
      - MARIADB_PASSWORD=userTech
      - MARIADB_ROOT_PASSWORD=userTech
    ports:
      - '3306:3306'
    volumes:
      - ./docs/db/fakeData.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: .
    container_name: techpass_app   
    ports:
      - '3000:3000'
      - '9000:9000'
    depends_on:
      - db